package seleniumBasics;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

public class ActionClass extends Base
{

	public static void main(String[] args)
	{
		ActionClass mouse=new ActionClass();
		mouse.initializeBrowser();
		try
		{
			mouse.keyboardAction();
		}
		catch(AWTException e)
		{
			//TODO Autogenerated catch block 
			e.printStackTrace();
		}
		//mouse.mouseAction();
		//mouse.mouseAction1();
		//mouse.driverCloseAndQuit();
	}
public void mouseAction()
{
	driver.navigate().to("https://selenium.qabible.in/drag-drop.php");
	//right click action
	WebElement rightClick=driver.findElement(By.xpath("//span[text()='Draggable n°1']"));
	Actions act=new Actions(driver);
	act.contextClick(rightClick).build().perform();
}
		public void mouseAction1()
		{
			//mouseHover action
	driver.navigate().to("https://selenium.qabible.in/drag-drop.php");
	WebElement mouseHover=driver.findElement(By.xpath("//a[text()='Drag and Drop']"));
	Actions act1=new Actions(driver);
	act1.moveToElement(mouseHover).build().perform();
}
		public void keyboardAction() throws AWTException 
		{
			Robot robot=new Robot ();
			robot.keyPress(KeyEvent.VK_CONTROL);  //KeyEvent Class 
			robot.keyPress(KeyEvent.VK_T);
			robot.keyRelease(KeyEvent.VK_CONTROL);
			robot.keyRelease(KeyEvent.VK_T);
		   }
}

	

